TELEGRAM_TOKEN: "your_telegram_bot_token"
TEELGRAM_CHAT_ID: "your_telegram_chat_id"

# Credentials for librelink
EMAIL: "your_librelink_username"
PASSWORD: "your_librelink_password"

# Time interval in minutes
INTERVAL: 5