TELEGRAM_TOKEN: ""
USER_TELEGRAM_CHAT_ID: ""

# Hospital telegram chat id
HOSPITAL_TELEGRAM_BOT_TOKEN: "hospital_telegram_bot_token"
HOSPITAL_TELEGRAM_CHAT_ID: "hospital_telegram_chat_id"

# Credentials for librelink
EMAIL: "pedromarting3@gmail.com"
PASSWORD: "Prueba23-"

# Time interval in minutes
INTERVAL: 1

# Minimun glucose level to send a message
MIN_GLUCOSE: 60