TELEGRAM_TOKEN: "7112651923:AAEI3sNRaHqKhB5Me1dq1NnIZknxHpJiaio"
USER_TELEGRAM_CHAT_ID: "913034824"

# Hospital telegram chat id
HOSPITAL_TELEGRAM_BOT_TOKEN: "hospital_telegram_bot_token"
HOSPITAL_TELEGRAM_CHAT_ID: "hospital_telegram_chat_id"

# Credentials for librelink
EMAIL: "pedromarting3@gmail.com"
PASSWORD: "Prueba23-"

# Time interval in minutes
INTERVAL: 1

# Minimun glucose level to send a message
MIN_GLUCOSE: 60